table 'Antal avslut'
	lineageTag: d4210af1-b2b6-4110-8c42-35f1dd17ecfa

	measure 'total Finish per Month' = sum('Antal avslut'[Value])
		formatString: 0
		lineageTag: f29439cb-55c7-4b49-8e36-3c989a680e5d

	measure 'Total Recruitment cost' =
			[total Finish per Month]*CALCULATE(
			    SUM(Hr_Cost[Value]),
			    Hr_Cost[Attribute] = "Career Journey"
			)
		formatString: #,0
		lineageTag: d913af61-d4cc-4e6f-b114-6bdeb1e7e23f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Recruitment cost per Postion' = ```
			VAR _RC = CALCULATE(SUM(Hr_Cost[Value]), Hr_Cost[Attribute] = "Career Journey", 'Dim Positions'[Positions] ="RC")*CALCULATE([total Finish per Month], 'Dim Positions'[Positions] ="RC")
			 VAR _BRC = CALCULATE(SUM(Hr_Cost[Value]), Hr_Cost[Attribute] = "Career Journey", 'Dim Positions'[Positions] ="BRC")*CALCULATE([total Finish per Month], 'Dim Positions'[Positions] ="BRC")
			 VAR _drift = CALCULATE(SUM(Hr_Cost[Value]), Hr_Cost[Attribute] = "Career Journey", 'Dim Positions'[Positions] ="Driftledare")*CALCULATE([total Finish per Month], 'Dim Positions'[Positions] ="Driftledare")
			VAR _crew = CALCULATE(SUM(Hr_Cost[Value]), Hr_Cost[Attribute] = "Career Journey", 'Dim Positions'[Positions] ="Crew member")*CALCULATE([total Finish per Month], 'Dim Positions'[Positions] ="Crew member")
			VAR _Traniee = CALCULATE(SUM(Hr_Cost[Value]), Hr_Cost[Attribute] = "Career Journey", 'Dim Positions'[Positions] ="Trainee")*CALCULATE([total Finish per Month], 'Dim Positions'[Positions] ="Trainee")
			RETURN
			_RC+_BRC+_drift+_crew+_Traniee 
			```
		formatString: 0
		lineageTag: 4d476bef-242c-4f07-bd8b-f9b8ccb89be0

		annotation PBI_FormatHint = {"isDecimal":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f5e0f303-65e5-43e0-b66e-60e458e32438
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Avslut
		dataType: string
		lineageTag: 36a7b3f9-3b45-4bfb-9c2e-c51821fa1d7a
		summarizeBy: none
		sourceColumn: Avslut

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: e5114dca-f3cd-4ace-8c20-58ca0e1634b9
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 8e5239c6-4a45-48ea-bd56-958c14592960
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2632124b-7a8b-47e3-8e41-73215b6ec928
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 63d52286-3f4f-4ec6-8338-fd5fca598fcb
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'First Characters'
		dataType: string
		lineageTag: 7738f145-4089-45be-8f57-c984d8b4855e
		summarizeBy: none
		sourceColumn: First Characters
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 970f3bb8-3139-47d5-83f9-bce15caadd2a
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition 'Antal avslut' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\dv1891\MAX Burgers AB\MAX Controlling Page - Documents\MAX Project\MAX Power BI\HR\Antal avslut restauragn 2024.xlsx"), null, true),
				    Blad1_Sheet = Source{[Item="Blad1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Blad1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Avslut", type text}, {"Tot. Antal % #(lf)avslut", type any}, {"Tot. Antal#(lf)avslut", type any}, {"Antal avslut #(lf)BRC", Int64.Type}, {"% avslut #(lf)BRC", type number}, {"Antal avslut#(lf)Driftledare", Int64.Type}, {"% avslut#(lf)Driftledare", type number}, {"Antal asvlut#(lf)Traniee", Int64.Type}, {"%  avslut #(lf)Traniee", type number}, {"Antal avslut#(lf)Crew member", Int64.Type}, {"% avslut#(lf)Crew member", type number}, {"Antal avslut#(lf)RC", Int64.Type}, {"% avslut #(lf)RC", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Date] <> null)),
				    #"Inserted Year" = Table.AddColumn(#"Filtered Rows", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted First Characters" = Table.AddColumn(#"Inserted Month Name", "First Characters", each Text.Start([Month Name], 3), type text),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Inserted First Characters", {"Date", "Avslut", "Year", "Month Name", "First Characters"}, "Attribute", "Value"),
				    #"Filtered Rows1" = Table.SelectRows(#"Unpivoted Columns", each ([Attribute] = "Antal asvlut#(lf)Traniee" or [Attribute] = "Antal avslut#(lf)Crew member" or [Attribute] = "Antal avslut#(lf)Driftledare" or [Attribute] = "Antal avslut#(lf)RC" or [Attribute] = "Antal avslut #(lf)BRC")),
				    #"Cleaned Text" = Table.TransformColumns(#"Filtered Rows1",{{"Attribute", Text.Clean, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"Attribute", Text.Trim, type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Trimmed Text","Antal avslut","",Replacer.ReplaceText,{"Attribute"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Antal asvlut","",Replacer.ReplaceText,{"Attribute"}),
				    #"Cleaned Text1" = Table.TransformColumns(#"Replaced Value1",{{"Attribute", Text.Clean, type text}}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Cleaned Text1",{{"Attribute", Text.Trim, type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Trimmed Text1",{{"Value", type number}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"First Characters"}, #"First Characters", {"Month"}, "First Characters.1", JoinKind.LeftOuter),
				    #"Expanded First Characters.1" = Table.ExpandTableColumn(#"Merged Queries", "First Characters.1", {"Index"}, {"Index"})
				in
				    #"Expanded First Characters.1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

