table 'MBRetention Extract Worker T'
	lineageTag: 4ce47bb8-1e29-49bb-936c-2f106a35af01

	measure 'Worked Weeks' = CALCULATE(sum('MBRetention Extract Worker T'[Weeks Worked]))
		formatString: 0
		lineageTag: 2f81c0e8-dad5-4eae-a580-6ad53355b846

	measure 'Worked Weeks avg' = AVERAGE('MBRetention Extract Worker T'[Weeks Worked])
		formatString: 0
		lineageTag: c0f365bc-264a-439a-9f26-31a85054be1e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Count = DISTINCTCOUNT('MBRetention Extract Worker T'[Employee ID])
		formatString: 0
		lineageTag: f03ab137-04b4-45a6-94b4-d29ec80a4c84

	column 'CF EE Worker Region'
		dataType: string
		lineageTag: e3c12223-54aa-452e-adb9-1b1cecce34ac
		summarizeBy: none
		sourceColumn: CF EE Worker Region

		annotation SummarizationSetBy = Automatic

	column 'CF EE Worker District'
		dataType: string
		lineageTag: 9f3f144e-b5fe-4a9c-8d3a-d8a56aa894b4
		summarizeBy: none
		sourceColumn: CF EE Worker District

		annotation SummarizationSetBy = Automatic

	column 'Supervisory Organization'
		dataType: string
		lineageTag: 3945f23c-469c-4ad2-bc42-2f9007b43c53
		summarizeBy: none
		sourceColumn: Supervisory Organization

		annotation SummarizationSetBy = Automatic

	column 'Job Profile'
		dataType: string
		lineageTag: 64b352cb-4f27-454b-8dff-7d919cb98e90
		summarizeBy: none
		sourceColumn: Job Profile

		annotation SummarizationSetBy = Automatic

	column 'Employee Type'
		dataType: string
		lineageTag: b5de74c3-2392-45e1-8726-0ae2124d80df
		summarizeBy: none
		sourceColumn: Employee Type

		annotation SummarizationSetBy = Automatic

	column 'Time Type'
		dataType: string
		lineageTag: c456f70e-134c-419f-907e-61f26b4a7bbe
		summarizeBy: none
		sourceColumn: Time Type

		annotation SummarizationSetBy = Automatic

	column 'Primary Termination Reason'
		dataType: string
		lineageTag: 9ba4d956-e48c-49d1-bb55-82e14c534dec
		summarizeBy: none
		sourceColumn: Primary Termination Reason

		annotation SummarizationSetBy = Automatic

	column 'Hire Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 75699bc4-e96d-448e-81d2-bbeed3410fcc
		summarizeBy: none
		sourceColumn: Hire Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Termination Date - All'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 11e75ef5-8eab-44d3-ab52-3bc316e1d755
		summarizeBy: none
		sourceColumn: Termination Date - All

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last Day of Work'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0b59d6e1-1569-4352-b31d-cb4e68bef13f
		summarizeBy: none
		sourceColumn: Last Day of Work

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Resignation Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 215b7291-2ff7-4278-86c1-7b8d07d4e44f
		summarizeBy: none
		sourceColumn: Resignation Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Resignation Date nr'
		dataType: double
		lineageTag: 4df97af8-94e2-462a-a41b-10e877a17c4c
		summarizeBy: sum
		sourceColumn: Resignation Date nr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Employee ID'
		dataType: string
		lineageTag: 78548a79-6808-42f1-8ae1-c8d81342cb65
		summarizeBy: none
		sourceColumn: Employee ID

		annotation SummarizationSetBy = Automatic

	column 'Days Worked'
		dataType: double
		formatString: 0
		lineageTag: e1f5c697-0c18-4517-9df9-d20c2d91f07e
		summarizeBy: sum
		sourceColumn: Days Worked

		annotation SummarizationSetBy = Automatic

	column 'Months Worked'
		dataType: double
		lineageTag: 5bcedcad-2556-418c-9ab9-56591505b5c7
		summarizeBy: sum
		sourceColumn: Months Worked

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Name'
		dataType: string
		lineageTag: f6b05db0-33e6-4cb8-856d-52315d26f3a3
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5df15990-93c6-43e8-841a-ce9925d8f31a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Weeks Worked'
		dataType: double
		lineageTag: 969c0425-bd0a-46d5-9ab9-a5f7e5336320
		summarizeBy: sum
		sourceColumn: Weeks Worked

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"MBRetention Extract Worker T","TableItemName":"Weeks Worked (bins)","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"MBRetention Extract Worker T","TableItemName":"Weeks Worked (groups)","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"MBRetention Extract Worker T","TableItemName":"Weeks Worked (groups) 2","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Weeks Worked (bins)' = ```
			VAR __Count = 30
			
			VAR __Min = MIN('MBRetention Extract Worker T'[Weeks Worked])
			
			VAR __Max = MAX('MBRetention Extract Worker T'[Weeks Worked])
			
			VAR __Difference = (__Max - __Min)
			
			VAR __Size = IF(__Difference > 0, __Difference / __Count, 1)
			
			VAR __BinNumber = 
				IF(
					ISBLANK('MBRetention Extract Worker T'[Weeks Worked]),
					BLANK(),
					ROUNDDOWN(('MBRetention Extract Worker T'[Weeks Worked] - __Min) / __Size, 0)
				)
			
			RETURN
				IF(
					ISBLANK('MBRetention Extract Worker T'[Weeks Worked]),
					BLANK(),
					__Min + (MIN(__BinNumber, __Count - 1) * __Size)
				)
			```
		lineageTag: a5916406-01e1-4917-aecf-35701fc089ae
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "MBRetention Extract Worker T"
				          }
				        },
				        "Property": "Weeks Worked"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"m","Entity":"MBRetention Extract Worker T"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"BinItem":{"Expression":{"Member":{"Expression":{"Discretize":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}},"Count":30}},"Member":"Min"}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Weeks Worked (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('MBRetention Extract Worker T'[Weeks Worked]),
				"(Blank)",
				'MBRetention Extract Worker T'[Weeks Worked] IN {0,
					5},
				"0 & 5",
				'MBRetention Extract Worker T'[Weeks Worked] IN {11,
					12,
					13,
					14,
					15,
					16,
					17,
					18,
					19,
					20,
					21,
					22,
					23,
					24,
					25,
					26,
					27,
					28,
					29,
					30},
				"11 & 12 & 13 & 14 & 15 & 16 & 17 & 18 & 19 & 20 & 21 & 22 & 23 & 24 & 25 & 26 & 27 & 28 & 29 & 30",
				'MBRetention Extract Worker T'[Weeks Worked] IN {6,
					7,
					8,
					9,
					10},
				"6 & 7 & 8 & 9 & 10",
				"Other"
			)
		lineageTag: b19cc9be-ff78-4dbe-81fc-6a3df00475c4
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "MBRetention Extract Worker T"
				          }
				        },
				        "Property": "Weeks Worked"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"m","Entity":"MBRetention Extract Worker T"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"0 & 5","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"Values":[[{"Literal":{"Value":"0D"}}],[{"Literal":{"Value":"5D"}}]]}}},{"DisplayName":"11 & 12 & 13 & 14 & 15 & 16 & 17 & 18 & 19 & 20 & 21 & 22 & 23 & 24 & 25 & 26 & 27 & 28 & 29 & 30","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"Values":[[{"Literal":{"Value":"11D"}}],[{"Literal":{"Value":"12D"}}],[{"Literal":{"Value":"13D"}}],[{"Literal":{"Value":"14D"}}],[{"Literal":{"Value":"15D"}}],[{"Literal":{"Value":"16D"}}],[{"Literal":{"Value":"17D"}}],[{"Literal":{"Value":"18D"}}],[{"Literal":{"Value":"19D"}}],[{"Literal":{"Value":"20D"}}],[{"Literal":{"Value":"21D"}}],[{"Literal":{"Value":"22D"}}],[{"Literal":{"Value":"23D"}}],[{"Literal":{"Value":"24D"}}],[{"Literal":{"Value":"25D"}}],[{"Literal":{"Value":"26D"}}],[{"Literal":{"Value":"27D"}}],[{"Literal":{"Value":"28D"}}],[{"Literal":{"Value":"29D"}}],[{"Literal":{"Value":"30D"}}]]}}},{"DisplayName":"6 & 7 & 8 & 9 & 10","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"Values":[[{"Literal":{"Value":"6D"}}],[{"Literal":{"Value":"7D"}}],[{"Literal":{"Value":"8D"}}],[{"Literal":{"Value":"9D"}}],[{"Literal":{"Value":"10D"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Uniq
		dataType: int64
		formatString: 0
		lineageTag: 62f41030-3185-41cf-b5f7-f7b228dc60bc
		summarizeBy: sum
		sourceColumn: Uniq

		annotation SummarizationSetBy = Automatic

	column 'Count Sum' = sum('MBRetention Extract Worker T'[Uniq])
		lineageTag: e13b56c9-f540-4056-b418-6e22214f8d72
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Weeks Worked (groups) 2' =
			SWITCH(
				TRUE,
				ISBLANK('MBRetention Extract Worker T'[Weeks Worked]),
				"(Blank)",
				'MBRetention Extract Worker T'[Weeks Worked] IN {0,
					1,
					2,
					3,
					4},
				"1M",
				'MBRetention Extract Worker T'[Weeks Worked] IN {5,
					6,
					7,
					8},
				"2M",
				'MBRetention Extract Worker T'[Weeks Worked] IN {9,
					10,
					11,
					12},
				"3M",
				'MBRetention Extract Worker T'[Weeks Worked] IN {13,
					14,
					15,
					16,
					17,
					18,
					19,
					20,
					21,
					22,
					23,
					24},
				"6M",
				'MBRetention Extract Worker T'[Weeks Worked] IN {25,
					26,
					27,
					28,
					29,
					30,
					31,
					32,
					33,
					34,
					35,
					36,
					37,
					38,
					39,
					40,
					41,
					42,
					43,
					44,
					45,
					46,
					47,
					48,
					49,
					50,
					51,
					52},
				"Year 1",
				'MBRetention Extract Worker T'[Weeks Worked] IN {53,
					54,
					55,
					56,
					57,
					58,
					59,
					60,
					61,
					62,
					63,
					64,
					66,
					67,
					68,
					69,
					70,
					71,
					72,
					73,
					74,
					75,
					76,
					77,
					78,
					79,
					81,
					82,
					83,
					84,
					85,
					86,
					87,
					88,
					89,
					90,
					91,
					93,
					94,
					96,
					97,
					99,
					100,
					101,
					102},
				"Year 1-2",
				"Year 2>"
			)
		lineageTag: ca037901-e840-4203-bb6c-9514feb6efa6
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "MBRetention Extract Worker T"
				          }
				        },
				        "Property": "Weeks Worked"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"m","Entity":"MBRetention Extract Worker T"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"1M","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"Values":[[{"Literal":{"Value":"0D"}}],[{"Literal":{"Value":"1D"}}],[{"Literal":{"Value":"2D"}}],[{"Literal":{"Value":"3D"}}],[{"Literal":{"Value":"4D"}}]]}}},{"DisplayName":"2M","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"Values":[[{"Literal":{"Value":"5D"}}],[{"Literal":{"Value":"6D"}}],[{"Literal":{"Value":"7D"}}],[{"Literal":{"Value":"8D"}}]]}}},{"DisplayName":"3M","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"Values":[[{"Literal":{"Value":"9D"}}],[{"Literal":{"Value":"10D"}}],[{"Literal":{"Value":"11D"}}],[{"Literal":{"Value":"12D"}}]]}}},{"DisplayName":"6M","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"Values":[[{"Literal":{"Value":"13D"}}],[{"Literal":{"Value":"14D"}}],[{"Literal":{"Value":"15D"}}],[{"Literal":{"Value":"16D"}}],[{"Literal":{"Value":"17D"}}],[{"Literal":{"Value":"18D"}}],[{"Literal":{"Value":"19D"}}],[{"Literal":{"Value":"20D"}}],[{"Literal":{"Value":"21D"}}],[{"Literal":{"Value":"22D"}}],[{"Literal":{"Value":"23D"}}],[{"Literal":{"Value":"24D"}}]]}}},{"DisplayName":"Year 1","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"Values":[[{"Literal":{"Value":"25D"}}],[{"Literal":{"Value":"26D"}}],[{"Literal":{"Value":"27D"}}],[{"Literal":{"Value":"28D"}}],[{"Literal":{"Value":"29D"}}],[{"Literal":{"Value":"30D"}}],[{"Literal":{"Value":"31D"}}],[{"Literal":{"Value":"32D"}}],[{"Literal":{"Value":"33D"}}],[{"Literal":{"Value":"34D"}}],[{"Literal":{"Value":"35D"}}],[{"Literal":{"Value":"36D"}}],[{"Literal":{"Value":"37D"}}],[{"Literal":{"Value":"38D"}}],[{"Literal":{"Value":"39D"}}],[{"Literal":{"Value":"40D"}}],[{"Literal":{"Value":"41D"}}],[{"Literal":{"Value":"42D"}}],[{"Literal":{"Value":"43D"}}],[{"Literal":{"Value":"44D"}}],[{"Literal":{"Value":"45D"}}],[{"Literal":{"Value":"46D"}}],[{"Literal":{"Value":"47D"}}],[{"Literal":{"Value":"48D"}}],[{"Literal":{"Value":"49D"}}],[{"Literal":{"Value":"50D"}}],[{"Literal":{"Value":"51D"}}],[{"Literal":{"Value":"52D"}}]]}}},{"DisplayName":"Year 1-2","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Weeks Worked"}}],"Values":[[{"Literal":{"Value":"53D"}}],[{"Literal":{"Value":"54D"}}],[{"Literal":{"Value":"55D"}}],[{"Literal":{"Value":"56D"}}],[{"Literal":{"Value":"57D"}}],[{"Literal":{"Value":"58D"}}],[{"Literal":{"Value":"59D"}}],[{"Literal":{"Value":"60D"}}],[{"Literal":{"Value":"61D"}}],[{"Literal":{"Value":"62D"}}],[{"Literal":{"Value":"63D"}}],[{"Literal":{"Value":"64D"}}],[{"Literal":{"Value":"66D"}}],[{"Literal":{"Value":"67D"}}],[{"Literal":{"Value":"68D"}}],[{"Literal":{"Value":"69D"}}],[{"Literal":{"Value":"70D"}}],[{"Literal":{"Value":"71D"}}],[{"Literal":{"Value":"72D"}}],[{"Literal":{"Value":"73D"}}],[{"Literal":{"Value":"74D"}}],[{"Literal":{"Value":"75D"}}],[{"Literal":{"Value":"76D"}}],[{"Literal":{"Value":"77D"}}],[{"Literal":{"Value":"78D"}}],[{"Literal":{"Value":"79D"}}],[{"Literal":{"Value":"81D"}}],[{"Literal":{"Value":"82D"}}],[{"Literal":{"Value":"83D"}}],[{"Literal":{"Value":"84D"}}],[{"Literal":{"Value":"85D"}}],[{"Literal":{"Value":"86D"}}],[{"Literal":{"Value":"87D"}}],[{"Literal":{"Value":"88D"}}],[{"Literal":{"Value":"89D"}}],[{"Literal":{"Value":"90D"}}],[{"Literal":{"Value":"91D"}}],[{"Literal":{"Value":"93D"}}],[{"Literal":{"Value":"94D"}}],[{"Literal":{"Value":"96D"}}],[{"Literal":{"Value":"97D"}}],[{"Literal":{"Value":"99D"}}],[{"Literal":{"Value":"100D"}}],[{"Literal":{"Value":"101D"}}],[{"Literal":{"Value":"102D"}}]]}}},{"DisplayName":"Year 2>"}]}

		annotation SummarizationSetBy = Automatic

	column Column =
			SWITCH(
			    TRUE(),
			    'MBRetention Extract Worker T'[Weeks Worked (groups) 2] = "1M", 1,
			    'MBRetention Extract Worker T'[Weeks Worked (groups) 2] = "2M", 2,
			    'MBRetention Extract Worker T'[Weeks Worked (groups) 2] = "3M", 3,
			    'MBRetention Extract Worker T'[Weeks Worked (groups) 2] = "6M", 6,
			    'MBRetention Extract Worker T'[Weeks Worked (groups) 2] = "Year 1", 12,
			    'MBRetention Extract Worker T'[Weeks Worked (groups) 2] = "Year 1-2", 24,
			    'MBRetention Extract Worker T'[Weeks Worked (groups) 2] = "Year 2>", 25,
			    BLANK()
			
			
			)
		formatString: 0
		lineageTag: 985a2b03-a111-4b45-9610-0e965638b700
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'MBRetention Extract Worker T' = m
		mode: import
		source = ```
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\dv1891\MAX Burgers AB\MAX Controlling Page - Documents\MAX Project\MAX Power BI\HR\240114 Retention V.2.xlsx"), null, true),
				    #"MBRetention Extract Worker T_Sheet" = Source{[Item="MBRetention Extract Worker T",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"MBRetention Extract Worker T_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CF EE Worker Region", type text}, {"CF EE Worker District", type text}, {"Supervisory Organization", type text}, {"Job Profile", type text}, {"Employee Type", type text}, {"Time Type", type text}, {"Primary Termination Reason", type text}, {"Hire Date", type date}, {"Termination Date - All", type date}, {"Last Day of Work", type date}, {"Resignation Date", type date}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Resignation Date nr", each if [Resignation Date] = null then 0 else 1),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Resignation Date nr", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Days Worked", each [#"Termination Date - All"] - [Hire Date]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Days Worked", Int64.Type}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type2", "Months Worked", each 
				    (Date.Year([#"Termination Date - All"]) - Date.Year([Hire Date])) * 12 +
				    (Date.Month([#"Termination Date - All"]) - Date.Month([Hire Date]))),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Weeks Worked", each Number.Round(Duration.Days([#"Termination Date - All"] - [Hire Date]) / 7)),
				    #"Inserted Month Name" = Table.AddColumn(#"Added Custom2", "Month Name", each Date.MonthName([#"Termination Date - All"]), type text),
				    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Month Name", {{"Month Name", each Text.Start(_, 3), type text}}),
				    #"Inserted Year" = Table.AddColumn(#"Extracted First Characters", "Year", each Date.Year([#"Termination Date - All"]), Int64.Type),
				    #"Filtered Rows" = Table.SelectRows(#"Inserted Year", each ([Year] = 2024)),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Filtered Rows",{{"Resignation Date nr", type number}, {"Days Worked", type number}, {"Months Worked", type number}, {"Weeks Worked", type number}}),
				    #"Added Custom3" = Table.AddColumn(#"Changed Type3", "Uniq", each 1),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom3",{{"Uniq", Int64.Type}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type4", each ([Weeks Worked] <> -5))
				in
				    #"Filtered Rows1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

