table FISCAL_DAYS
	lineageTag: f3fce158-fb81-4602-bd06-a4e4351ab654

	column Days
		dataType: string
		lineageTag: 8cbb4607-81ab-4e7b-889f-8e413a667e7f
		summarizeBy: none
		sourceColumn: Days
		sortByColumn: Rank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: f440aa07-b052-4f49-8616-36fb8b6f1b80
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Rank
		dataType: string
		lineageTag: f663b839-b350-4dee-8a13-6e88872b91b8
		summarizeBy: none
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	partition FISCAL_DAYS = m
		mode: import
		queryGroup: dim
		source =
				let
				    Source = Snowflake.Databases("ya34293.west-europe.azure.snowflakecomputing.com","ANALYSIS"),
				    GOLD_TEST_Database = Source{[Name="GOLD_TEST",Kind="Database"]}[Data],
				    CORE_Schema = GOLD_TEST_Database{[Name="CORE",Kind="Schema"]}[Data],
				    D_FISCAL_DATE_View = CORE_Schema{[Name="D_FISCAL_DATE",Kind="View"]}[Data],
				    FISCAL_DAY_OF_WEEK_LONG1 = D_FISCAL_DATE_View[FISCAL_DAY_OF_WEEK_SHORT],
				    #"Removed Duplicates" = List.Distinct(FISCAL_DAY_OF_WEEK_LONG1),
				    #"Converted to Table" = Table.FromList(#"Removed Duplicates", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Days"}}),
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns", "Index", 1, 1, Int64.Type),
				    #"Added Conditional Column" = Table.AddColumn(#"Added Index", "Rank", each if [Days] = "Mon" then 1 else if [Days] = "Tue" then 2 else if [Days] = "Wed" then 3 else if [Days] = "Thu" then 4 else if [Days] = "Fri" then 5 else if [Days] = "Sat" then 6 else if [Days] = "Sun" then 7 else null)
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

