table 'Current Month'
	isHidden
	lineageTag: 9b44b546-3f96-42c7-807b-f89d8af4712c

	column 'Last Completed Month'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 6c9aae3a-1462-4b76-b555-a199e6bbe5c1
		summarizeBy: none
		sourceColumn: Last Completed Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CurrentMonth
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f231cf15-8779-4f31-98c1-84ea521665fa
		summarizeBy: sum
		sourceColumn: CurrentMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Current Month' = m
		mode: import
		queryGroup: Time
		source = ```
				let
				    // Get the current date and time
				    CurrentDateTime = DateTime.LocalNow(),
				    
				    // Get the first day of the current month
				    StartOfCurrentMonth = Date.StartOfMonth(CurrentDateTime),
				    
				    // Subtract one month to get the first day of the last completed month
				    StartOfLastCompletedMonth = Date.AddMonths(StartOfCurrentMonth, 0),
				    
				    // Create a table with the last completed month
				    #"Converted to Table" = #table(1, {{StartOfLastCompletedMonth}}),
				    
				    // Rename the column to "Last Completed Month"
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table", {{"Column1", "Last Completed Month"}}),
				    
				    // Change the column type to date
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Last Completed Month", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Last Completed Month]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Last Completed Month]), Int64.Type),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Inserted Month", {{"Year", type text}, {"Month", type text}}, "en-US"),{"Year", "Month"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Merged"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Merged Columns",{{"Merged", "CurrentMonth"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"CurrentMonth", Int64.Type}})
				in
				    #"Changed Type1"
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

