table 'Dynamic Format Strings'
	isHidden
	lineageTag: a13e8131-04a7-4d1b-b5f9-ed5361e57dd5

	measure 'Selected Format' = ```
			SELECTEDVALUE('Dynamic Format Strings'[Unit Formatting  String]) 
			```
		isHidden
		lineageTag: 3983cb83-573a-4211-94d1-3df28de99bed

		changedProperty = IsHidden

	column Unit
		dataType: string
		isHidden
		lineageTag: 67d66331-9062-4b3b-8486-f91ecf9eda59
		summarizeBy: none
		sourceColumn: Unit
		sortByColumn: Rank

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Unit Formatting  String'
		dataType: string
		isHidden
		lineageTag: c46b9b6c-c135-4fe8-b42d-2fe0465eba1d
		summarizeBy: none
		sourceColumn: Unit Formatting  String

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Rank
		dataType: string
		isHidden
		lineageTag: 3538dbb5-b217-4d8a-ad1c-82a12bdcfca7
		summarizeBy: none
		sourceColumn: Rank

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Dynamic Format Strings' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCsnILy1OzEspVtJRUtZRVjYA0kZKsTrRSr6ZOTmZ+XnFCjAZHR09A5C0IVjaLz8vFSwDEjJWio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Unit = _t, #"Unit Formatting  String" = _t, Rank = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Unit", type text}, {"Unit Formatting  String", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

