table 'Latest Complete Month'
	isHidden
	lineageTag: d3591191-dd29-4ff6-9811-44578d8727ed

	column 'Last Completed Month'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: e0fb801c-3451-49f6-a17f-415511b96830
		summarizeBy: none
		sourceColumn: Last Completed Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LastCompletedMonth
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0a1ac76b-5ac2-4a02-afc4-b4428be307d5
		summarizeBy: sum
		sourceColumn: LastCompletedMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Latest Complete Month' = m
		mode: import
		queryGroup: Time
		source = ```
				let
				    // Get the current date and time
				    CurrentDateTime = DateTime.LocalNow(),
				    
				    // Get the first day of the current month
				    StartOfCurrentMonth = Date.StartOfMonth(CurrentDateTime),
				    
				    // Subtract one month to get the first day of the last completed month
				    StartOfLastCompletedMonth = Date.AddMonths(StartOfCurrentMonth, -1),
				    
				    // Create a table with the last completed month
				    #"Converted to Table" = #table(1, {{StartOfLastCompletedMonth}}),
				    
				    // Rename the column to "Last Completed Month"
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table", {{"Column1", "Last Completed Month"}}),
				    
				    // Change the column type to date
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Last Completed Month", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Last Completed Month]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Last Completed Month]), Int64.Type),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Inserted Month", {{"Year", type text}, {"Month", type text}}, "en-US"),{"Year", "Month"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Merged"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Merged Columns",{{"Merged", "LastCompletedMonth"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"LastCompletedMonth", Int64.Type}})
				in
				    #"Changed Type1"
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

