table 'Current Month'
	lineageTag: 31ecae9e-8f22-4a35-bec5-b1598c2d0077

	column 'Last Completed Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 25a36cd5-cd07-4b60-a0b1-7b919ba47747
		summarizeBy: none
		sourceColumn: Last Completed Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CurrentMonth
		dataType: int64
		formatString: 0
		lineageTag: 343db9aa-3294-4ca6-a582-d9de017bf6b8
		summarizeBy: sum
		sourceColumn: CurrentMonth

		annotation SummarizationSetBy = Automatic

	partition 'Current Month' = m
		mode: import
		source = ```
				let
				    // Get the current date and time
				    CurrentDateTime = DateTime.LocalNow(),
				    
				    // Get the first day of the current month
				    StartOfCurrentMonth = Date.StartOfMonth(CurrentDateTime),
				    
				    // Subtract one month to get the first day of the last completed month
				    StartOfLastCompletedMonth = Date.AddMonths(StartOfCurrentMonth, 0),
				    
				    // Create a table with the last completed month
				    #"Converted to Table" = #table(1, {{StartOfLastCompletedMonth}}),
				    
				    // Rename the column to "Last Completed Month"
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table", {{"Column1", "Last Completed Month"}}),
				    
				    // Change the column type to date
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Last Completed Month", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Last Completed Month]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Last Completed Month]), Int64.Type),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Inserted Month", {{"Year", type text}, {"Month", type text}}, "en-US"),{"Year", "Month"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Merged"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Merged Columns",{{"Merged", "CurrentMonth"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"CurrentMonth", Int64.Type}})
				in
				    #"Changed Type1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

