table LCM
	lineageTag: d02c5484-91bd-405c-8eb0-139b4476bdcc

	column Refresh
		dataType: dateTime
		formatString: General Date
		lineageTag: afa70879-1afb-49bd-ae3b-d7f5f461616c
		summarizeBy: none
		sourceColumn: Refresh

		annotation SummarizationSetBy = Automatic

	column 'Last Completed Day'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1ef83ab3-c1bd-473c-afe0-0cc025199012
		summarizeBy: none
		sourceColumn: Last Completed Day

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Rolling 12M Start'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3003d401-e81e-42de-989e-25331f0159ad
		summarizeBy: none
		sourceColumn: Rolling 12M Start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition LCM = m
		mode: import
		source =
				let
				    // Get the current date and time with timezone adjustment
				    Source = DateTimeZone.SwitchZone(DateTimeZone.LocalNow(), 10),
				
				    // Convert to a table
				    #"Converted to Table" = #table(1, {{Source}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table", {{"Column1", "Refresh"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Refresh", type datetime}}),
				
				    // Calculate the last completed day (previous day's date)
				    #"Last Completed Day" = Table.AddColumn(#"Changed Type", "Last Completed Day", each Date.AddDays(DateTime.Date([Refresh]), -1), type date),
				
				    // Calculate the last completed month (first day of the previous month)
				    #"Last Completed Month" = Table.AddColumn(#"Last Completed Day", "Last Completed Month", each Date.StartOfMonth(Date.AddMonths([Refresh], -1)), type date),
				
				    // Calculate the rolling 12-month start date (12 months before the last completed month)
				    #"Rolling 12M Start" = Table.AddColumn(#"Last Completed Month", "Rolling 12M Start", each Date.AddMonths([Last Completed Month], -11), type date),
				
				    // Set the rolling 12-month end date to the last completed month
				    #"Rolling 12M End" = Table.AddColumn(#"Rolling 12M Start", "Rolling 12M End", each [Last Completed Month], type date),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Rolling 12M End",{{"Rolling 12M Start", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Last Completed Month", "Rolling 12M End"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

